version: 2

models:

  - name: nypd_arrests_dn
    description: "Denormalized data for analysis"
    columns:
      - name: arrest_key
        tests:
          - not_null
      - name: arrest_date
        tests:
          - not_null
      - name: ofns_desc
        tests:
          - not_null
      - name: law_cat_cd
        tests:
          - not_null
      - name: arrest_boro
        tests:
          - not_null
      - name: precinct_name
        tests:
          - not_null
      - name: precinct_boro
        tests:
          - not_null
      - name: jurisdiction_code
        tests:
          - not_null
      - name: age_group
        tests:
          - not_null
      - name: perp_sex
        tests:
          - not_null
      - name: perp_race
        tests:
          - not_null
      - name: latitude
        tests:
          - not_null
      - name: longitude
        tests:
          - not_null
      - name: sched_id
        tests:
          - not_null
